filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app/backend/*.log
      - /var/log/app/frontend/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
